# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  Капибара — Multi-stage Dockerfile                                          ║
# ║  Stage 1 deps    → install production + dev dependencies                   ║
# ║  Stage 2 builder → run `next build` (outputs .next/standalone)             ║
# ║  Stage 3 runner  → minimal production image (~150 MB)                      ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# ── Pinned base image ─────────────────────────────────────────────────────────
ARG NODE_VERSION=20
ARG ALPINE_VERSION=3.20

# ─────────────────────────────────────────────────────────── Stage 1: deps ────
FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS deps

# libc6-compat is required for some native node modules on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy manifests first so this layer is cached unless deps change
COPY package.json package-lock.json* ./

# Use `npm ci` for reproducible installs; include devDeps for the build stage
RUN npm ci


# ─────────────────────────────────────────────────────────── Stage 2: builder ─
FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS builder

WORKDIR /app

# Bring installed node_modules from the deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy the full source
COPY . .

# Disable telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

# Build the application.
# next.config.ts has output: "standalone" which produces .next/standalone/
RUN npm run build


# ─────────────────────────────────────────────────────────── Stage 3: runner ──
FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# next/image can need sharp; alpine already ships libc6-compat but add it anyway
RUN apk add --no-cache libc6-compat

# ── Security: run as non-root ─────────────────────────────────────────────────
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# ── Copy only the files needed to run the server ─────────────────────────────
# 1. Public assets (static files served by Next.js)
COPY --from=builder /app/public ./public

# 2. Standalone server bundle (includes a trimmed node_modules)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# 3. Static assets generated by Next.js (JS chunks, CSS, images)
#    They must be at .next/static relative to the standalone server.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

# Default port; override with -e PORT=xxxx or in docker-compose
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# standalone output puts server.js directly at /app/server.js
CMD ["node", "server.js"]
